routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('usuarios', 'usuarioController');
Route::resource('clientes', 'clienteController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/clienteModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class clienteModel extends Model
{
    protected $table='clientes';
}

app/usuarioModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class usuarioModel extends Model
{
    protected $table='usuarios';
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/clienteController.php
<?php

namespace App\Http\Controllers;

use App\clienteModel;
use App\usuarioModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class clienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //return json_encode(clienteModel::all());


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try
        {
            DB::beginTransaction();
            $clienteGuardar = new clienteModel();
            $clienteGuardar->nombres=$request->nombres;
            $clienteGuardar->apellidos=$request->apellidos;
            $clienteGuardar->cedula=$request->cedula;
            $clienteGuardar->telefono=$request->telefono;
            $clienteGuardar->direccion=$request->direccion;
            $clienteGuardar->save();
            DB::commit();
            return 1;
        }catch(\Illuminate\Database\QueryException $e){
            return $e->getMessage();
            DB::rollBack();
            return 10;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\clienteModel  $clienteModel
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return json_encode(clienteModel::find($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\clienteModel  $clienteModel
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\clienteModel  $clienteModel
     * @return \Illuminate\Http\Response
     */
    public function update($id,Request $request)
    {
        $clienteGuardar = clienteModel::find($id);
        $clienteGuardar->nombres=$request->nombres;
        $clienteGuardar->apellidos=$request->apellidos;
        $clienteGuardar->cedula=$request->cedula;
        $clienteGuardar->telefono=$request->telefono;
        $clienteGuardar->direccion=$request->direccion;
        $clienteGuardar->save();
        return 1;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\clienteModel  $clienteModel
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        clienteModel::find($id)->delete();
        return 1;
    }
}

app/Http/Controllers/usuarioController.php
<?php

namespace App\Http\Controllers;

use App\usuarioModel;
use Illuminate\Http\Request;
use Hash;
use Illuminate\Support\Facades\DB;
use Mail;
use Redirect;
use Session;


class usuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        return json_encode(usuarioModel::all());
        $usuarios = usuarioModel::all();
        return view('user.index', compact('usuarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){

        $user_g = new usuarioModel();
        $user_g->nombres=$request->nombres;
        $user_g->apellidos=$request->apellidos;
        $user_g->cedula=$request->cedula;
        $user_g->genero=$request->genero;
        $user_g->correo=$request->correo;
        $user_g->clave=bcrypt($request->nombres);
        $user_g->save();
        return redirect('usuarios');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\usuarioModel  $usuarioModel
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = usuarioModel::find($id);
        return view('user.view', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\usuarioModel  $usuarioModel
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = usuarioModel::find($id);
        return view('user.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\usuarioModel  $usuarioModel
     * @return \Illuminate\Http\Response
     */
    public function update($id, Request $request)
    {
        $usuarioGuardar= usuarioModel::find($id);
        $usuarioGuardar->nombres=$request->nombres;
        $usuarioGuardar->apellidos=$request->apellidos;
        $usuarioGuardar->cedula=$request->cedula;
        $usuarioGuardar->genero=$request->genero;
        $usuarioGuardar->correo=$request->correo;
        $usuarioGuardar->save();

        return redirect('usuarios');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\usuarioModel  $usuarioModel
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        usuarioModel::find($id)->delete();
        return redirect('usuarios');
    }
}

resources/views/user/create.blade.php
@extends('user.parent')


@section('main')

    <form method="post" action="{{route('usuarios.store')}}" enctype="multipart/form-data">
        @csrf
        <div class="card" style="margin: 10px 10px 10px 10px; padding: 20px 20px 0px 20px;  margin-top: 150px; background:rgba(51,51,51, 0.5);" >
            <form>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <input type="text" name="nombres" class="form-control input-lg" placeholder="Ingrese Sus Nombres">
                    </div>
                    <div class="form-group col-md-6">
                        <input type="text" name="apellidos" class="form-control input-lg" placeholder="Ingrese Sus Nombres">
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <input type="number" name="cedula" class="form-control input-lg" placeholder="Ingrese Su Número De Cédula">
                    </div>
                    <div class="form-group col-md-6">
                        <input type="text" name="genero" class="form-control input-lg" placeholder="Ingrese Su Género">
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <input type="email" name="correo" class="form-control input-lg" placeholder="Ingrese Correo Electrónico">
                    </div>
                    <div class="form-group col-md-6">
                        <input type="password" name="clave" class="form-control input-lg" placeholder="Ingrese Su Clave">
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <button type="submit" class="btn btn-outline-success col-md-12" value="Add" name="add">REGISTRARSE</button>
                    </div>
                    <div class="form-group col-md-6">
                        <button type="submit" class="btn btn-outline-primary col-md-12" href="{{ route('usuarios.index') }}">CANCELAR</button>
                    </div>
                </div>
            </form>
        </div>
    </form>
@endsection

resources/views/user/edit.blade.php
@extends('user.parent')

@section('main')

    <div align="right">
        <a href="{{route('usuarios.index')}}" class="btn btn-outline-danger">ATRAS</a>
    </div>

    <br>

    <form method="post" action="{{route('usuarios.update', $data->id)}}"
    enctype="multipart/form-data">

        @csrf
        @method('PATCH')
            <div class="card" style="margin: 10px 10px 10px 10px; padding: 20px 20px 0px 20px;  margin-top: 150px; background:rgba(51,51,51, 0.5);" >
                <form>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <input type="text" name="nombres" class="form-control input-lg" value="{{$data->nombres}}">
                        </div>
                        <div class="form-group col-md-6">
                            <input type="text" name="apellidos" class="form-control input-lg" value="{{$data->apellidos}}">
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <input type="number" name="cedula" class="form-control input-lg" value="{{$data->cedula}}">
                        </div>
                        <div class="form-group col-md-6">
                            <input type="text" name="genero" class="form-control input-lg" value="{{$data->genero}}">
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <input type="email" name="correo" class="form-control input-lg" value="{{$data->correo}}">
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <button type="submit" class="btn btn-outline-success col-md-12" value="Add" name="add">ACTUALIZAR</button>
                        </div>
                    </div>
                </form>
            </div>
    </form>

@endsection

resources/views/user/index.blade.php
@extends('user.parent')

@section('main')


        <div class="row">
            <div class="col">
                <table class="table table-bordered table-hover" >
                    <thead class="thead-dark">
                    <tr>
                        <th >N°</th>
                        <th >NOMBRES</th>
                        <th >APELLIDOS</th>
                        <th >CEDULA</th>
                        <th >GÉNERO</th>
                        <th >CORREO</th>
                        <th class="text-center">
                            <a href="{{route('usuarios.create')}}" class="btn btn-outline-success">AGREGAR</a>
                        </th>
                    </tr>
                    </thead>
                @foreach($usuarios as $user)
                        <tbody>
                        <tr>
                            <td>{{$user->id}}</td>
                            <td>{{$user->nombres}}</td>
                            <td>{{$user->apellidos}}</td>
                            <td>{{$user->cedula}}</td>
                            <td>{{$user->genero}}</td>
                            <td>{{$user->correo}}</td>
                            <td class="text-center" style="width: auto; display: flex;justify-content: space-around;">
                                <a style="height: 40px;" href="{{route('usuarios.show', $user->id)}}" class="btn btn-outline-info">VER</a>
                                <a  style="height: 40px;"href="{{route('usuarios.edit', $user->id)}}" class="btn btn-outline-warning">EDITAR</a>
                                <form action="{{route('usuarios.destroy', $user->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <a style="height: 40px;" class="btn btn-outline-danger">ELIMINAR</a>
                                </form>
                            </td>
                        </tr>
                        </tbody>
                    @endforeach
                </table>
            </div>
        </div>


{{--    {!! $usuarios->link() !!}--}}
@endsection

resources/views/user/parent.blade.php
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TALLER DISTRIBUIDOS</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1' name='viewport'/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body style="background-color: rgba(119, 216, 69, 0.5)">
<div class="container" >
    <div class="row">
        <div class="col">
            <h1 align="center">USUARIOS</h1>
        </div>
    </div>
    @yield('main')
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

resources/views/user/view.blade.php
@extends('user.parent')

@section('main')

    <div class="jumbotron text-center">

        <div align="right">
            <a href="{{route('usuarios.index')}}" class="btn btn-outline-danger">ATRAS</a>
        </div>
            <h3>Nombres: {{$data->nombres}}</h3>
            <h3>Apellidos: {{$data->apellidos}}</h3>
            <h3>Cedula: {{$data->cedula}}</h3>
            <h3>Genero: {{$data->genero}}</h3>
            <h3>Correo: {{$data->correo}}</h3>


    </div>

@endsection